#! /bin/bash
#
# Author: Simone
#
# /etc/init.d/beerlog
#
### BEGIN INIT INFO
# Provides: Logbeer
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  2 3 4 5 S
# Default-Stop:   0 1 2 6
# Short-Description: Logbeer process
# Description:    Runs up the logbeer daemon process
### END INIT INFO

case "$1" in
	start)
		echo "Starting logbeer daemon"
		python /usr/share/logbeer/logbeer.py start
		;;
	stop) 
		echo "Stopping logbeer daemon"
		python /usr/share/logbeer/logbeer.py stop
		;;
	restart)
		echo "Restarting logbeer daemon"
		python /usr/share/logbeer/logbeer.py restart
		;;
	*)
		echo "Usage: /etc/init.d/logbeer {start|stop|restart}"
		exit 1
		;;
esac

exit 0
